;; source files
(set @m_files     (filelist "^objc/.*.m$"))

(set SYSTEM ((NSString stringWithShellCommand:"uname") chomp))
(case SYSTEM
      ("Darwin"
               (set @arch (list "x86_64"))
               (set @cflags "-g -I /usr/include/libxml2 -fobjc-arc")
               (set @ldflags "-framework Foundation -lxml2"))
      ("Linux"
              (set @arch (list "x86_64"))
              (set gnustep_flags ((NSString stringWithShellCommand:"gnustep-config --objc-flags") chomp))
              (set gnustep_libs ((NSString stringWithShellCommand:"gnustep-config --base-libs") chomp))
              (set @cflags "-g -I /usr/include/libxml2 -DLINUX -I/usr/local/include #{gnustep_flags} -fconstant-string-class=NSConstantString -fobjc-nonfragile-abi -fobjc-arc -fblocks")
              (set @ldflags "#{gnustep_libs} -lxml2"))
      (else nil))

;; framework description
(set @framework "AgentXML")
(set @framework_identifier "io.agent.xml")
(set @framework_creator_code "????")

(compilation-tasks)
(framework-tasks)

(task "default" => "framework")


